// =============================================================================
// Bakemachi (化け町) — Chapter 1 Vocabulary Database
// Contemporary Japan setting with supernatural combat elements.
//
// introductionLevel controls kanji rollout:
//   1 = basic kanji shown from the very start (人, 大, 日, 一, etc.)
//   2 = introduced after some play time (店, 駅, 食, etc.)
//   3 = introduced later in chapter (攻撃, 防御, 化け物, etc.)
// Words with introductionLevel > player's current chapter display in kana.
// =============================================================================

import type { Word } from './types';

export const VOCABULARY: Word[] = [
  // ---------------------------------------------------------------------------
  // 1. GREETINGS & ESSENTIALS (~8 words)
  // ---------------------------------------------------------------------------
  {
    id: 'w_konnichiwa',
    kanji: 'こんにちは',
    kana: 'こんにちは',
    romaji: 'konnichiwa',
    meaning: 'hello; good afternoon',
    jlptLevel: 5,
    partOfSpeech: 'expression',
    tags: ['chapter-1', 'greeting'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'こんにちは、元気ですか？',
      english: 'Hello, how are you?',
    },
  },
  {
    id: 'w_youkoso',
    kanji: 'ようこそ',
    kana: 'ようこそ',
    romaji: 'youkoso',
    meaning: 'welcome',
    jlptLevel: 5,
    partOfSpeech: 'expression',
    tags: ['chapter-1', 'greeting'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'ようこそ日本へ！',
      english: 'Welcome to Japan!',
    },
  },
  {
    id: 'w_sayounara',
    kanji: 'さようなら',
    kana: 'さようなら',
    romaji: 'sayounara',
    meaning: 'goodbye',
    jlptLevel: 5,
    partOfSpeech: 'expression',
    tags: ['chapter-1', 'greeting'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'さようなら、また明日！',
      english: 'Goodbye, see you tomorrow!',
    },
  },
  {
    id: 'w_sumimasen',
    kanji: 'すみません',
    kana: 'すみません',
    romaji: 'sumimasen',
    meaning: 'excuse me; I\'m sorry',
    jlptLevel: 5,
    partOfSpeech: 'expression',
    tags: ['chapter-1', 'greeting'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'すみません、駅はどこですか？',
      english: 'Excuse me, where is the station?',
    },
  },
  {
    id: 'w_arigatou',
    kanji: 'ありがとう',
    kana: 'ありがとう',
    romaji: 'arigatou',
    meaning: 'thank you',
    jlptLevel: 5,
    partOfSpeech: 'expression',
    tags: ['chapter-1', 'greeting'],
    introductionLevel: 1,
  },
  {
    id: 'w_hai',
    kanji: 'はい',
    kana: 'はい',
    romaji: 'hai',
    meaning: 'yes',
    jlptLevel: 5,
    partOfSpeech: 'expression',
    tags: ['chapter-1', 'greeting'],
    introductionLevel: 1,
  },
  {
    id: 'w_iie',
    kanji: 'いいえ',
    kana: 'いいえ',
    romaji: 'iie',
    meaning: 'no',
    jlptLevel: 5,
    partOfSpeech: 'expression',
    tags: ['chapter-1', 'greeting'],
    introductionLevel: 1,
  },
  {
    id: 'w_nihongo',
    kanji: '日本語',
    kana: 'にほんご',
    romaji: 'nihongo',
    meaning: 'Japanese (language)',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'greeting'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: '日本語をべんきょうしています。',
      english: 'I am studying Japanese.',
    },
  },
  {
    id: 'w_onegai',
    kanji: 'お願い',
    kana: 'おねがい',
    romaji: 'onegai',
    meaning: 'please; request',
    jlptLevel: 5,
    partOfSpeech: 'expression',
    tags: ['chapter-1', 'greeting'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'お願いします。',
      english: 'Please. / I\'d appreciate it.',
    },
  },
  {
    id: 'w_daijoubu',
    kanji: '大丈夫',
    kana: 'だいじょうぶ',
    romaji: 'daijoubu',
    meaning: 'okay; all right',
    jlptLevel: 5,
    partOfSpeech: 'na-adjective',
    tags: ['chapter-1', 'greeting'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: '大丈夫ですか？',
      english: 'Are you okay?',
    },
  },
  {
    id: 'w_ohayou',
    kanji: 'おはよう',
    kana: 'おはよう',
    romaji: 'ohayou',
    meaning: 'good morning',
    jlptLevel: 5,
    partOfSpeech: 'expression',
    tags: ['chapter-1', 'greeting'],
    introductionLevel: 1,
  },
  {
    id: 'w_irasshaimase',
    kanji: 'いらっしゃいませ',
    kana: 'いらっしゃいませ',
    romaji: 'irasshaimase',
    meaning: 'welcome (to a shop)',
    jlptLevel: 5,
    partOfSpeech: 'expression',
    tags: ['chapter-1', 'greeting'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'いらっしゃいませ！何をお探しですか？',
      english: 'Welcome! What are you looking for?',
    },
  },

  // ---------------------------------------------------------------------------
  // 2. PEOPLE (~8 words)
  // ---------------------------------------------------------------------------
  {
    id: 'w_hito',
    kanji: '人',
    kana: 'ひと',
    romaji: 'hito',
    meaning: 'person',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'person'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'あの人は誰ですか？',
      english: 'Who is that person?',
    },
  },
  {
    id: 'w_watashi',
    kanji: '私',
    kana: 'わたし',
    romaji: 'watashi',
    meaning: 'I; me',
    jlptLevel: 5,
    partOfSpeech: 'pronoun',
    tags: ['chapter-1', 'person'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: '私は学生です。',
      english: 'I am a student.',
    },
  },
  {
    id: 'w_tomodachi',
    kanji: '友達',
    kana: 'ともだち',
    romaji: 'tomodachi',
    meaning: 'friend',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'person'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '友達とコンビニに行きました。',
      english: 'I went to the convenience store with a friend.',
    },
  },
  {
    id: 'w_ten_in',
    kanji: '店員',
    kana: 'てんいん',
    romaji: 'ten\'in',
    meaning: 'shop clerk; store employee',
    jlptLevel: 4,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'person'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '店員さんが笑っています。',
      english: 'The store clerk is smiling.',
    },
  },
  {
    id: 'w_sensei',
    kanji: '先生',
    kana: 'せんせい',
    romaji: 'sensei',
    meaning: 'teacher; master',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'person'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: '先生、おはようございます。',
      english: 'Good morning, teacher.',
    },
  },
  {
    id: 'w_gakusei',
    kanji: '学生',
    kana: 'がくせい',
    romaji: 'gakusei',
    meaning: 'student',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'person'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: '学生がたくさんいます。',
      english: 'There are many students.',
    },
  },
  {
    id: 'w_kodomo',
    kanji: '子供',
    kana: 'こども',
    romaji: 'kodomo',
    meaning: 'child',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'person'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '子供が公園で遊んでいます。',
      english: 'The children are playing in the park.',
    },
  },
  {
    id: 'w_rinjin',
    kanji: '隣人',
    kana: 'りんじん',
    romaji: 'rinjin',
    meaning: 'neighbor',
    jlptLevel: 3,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'person'],
    introductionLevel: 3,
    exampleSentence: {
      japanese: '隣人の様子がおかしい。',
      english: 'Something is off about the neighbor.',
    },
  },

  // ---------------------------------------------------------------------------
  // 3. CONTEMPORARY PLACES (~8 words)
  // ---------------------------------------------------------------------------
  {
    id: 'w_bakemachi',
    kanji: '化け町',
    kana: 'ばけまち',
    romaji: 'bakemachi',
    meaning: 'Bakemachi (lit. monster town)',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'place'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'ようこそ化け町へ！',
      english: 'Welcome to Bakemachi!',
    },
  },
  {
    id: 'w_konbini',
    kanji: 'コンビニ',
    kana: 'コンビニ',
    romaji: 'konbini',
    meaning: 'convenience store',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'place'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'コンビニでお弁当を買いました。',
      english: 'I bought a bento at the convenience store.',
    },
  },
  {
    id: 'w_eki',
    kanji: '駅',
    kana: 'えき',
    romaji: 'eki',
    meaning: 'train station',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'place'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '駅まで歩きます。',
      english: 'I walk to the station.',
    },
  },
  {
    id: 'w_gakkou',
    kanji: '学校',
    kana: 'がっこう',
    romaji: 'gakkou',
    meaning: 'school',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'place'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: '学校は駅の近くにあります。',
      english: 'The school is near the station.',
    },
  },
  {
    id: 'w_kouen',
    kanji: '公園',
    kana: 'こうえん',
    romaji: 'kouen',
    meaning: 'park',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'place'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '夜の公園は怖い。',
      english: 'The park at night is scary.',
    },
  },
  {
    id: 'w_apaato',
    kanji: 'アパート',
    kana: 'アパート',
    romaji: 'apaato',
    meaning: 'apartment',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'place'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: '私のアパートは古いです。',
      english: 'My apartment is old.',
    },
  },
  {
    id: 'w_mise',
    kanji: '店',
    kana: 'みせ',
    romaji: 'mise',
    meaning: 'shop; store',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'place'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: 'あの店は何の店ですか？',
      english: 'What kind of shop is that?',
    },
  },
  {
    id: 'w_michi',
    kanji: '道',
    kana: 'みち',
    romaji: 'michi',
    meaning: 'road; path',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'place'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: 'この道は暗い。',
      english: 'This road is dark.',
    },
  },
  {
    id: 'w_byouin',
    kanji: '病院',
    kana: 'びょういん',
    romaji: 'byouin',
    meaning: 'hospital',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'place'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '病院に行かなければなりません。',
      english: 'I have to go to the hospital.',
    },
  },

  // ---------------------------------------------------------------------------
  // 4. DAILY LIFE ITEMS (~8 words)
  // ---------------------------------------------------------------------------
  {
    id: 'w_densha',
    kanji: '電車',
    kana: 'でんしゃ',
    romaji: 'densha',
    meaning: 'train',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'daily-life'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '電車が来ます。',
      english: 'The train is coming.',
    },
  },
  {
    id: 'w_denwa',
    kanji: '電話',
    kana: 'でんわ',
    romaji: 'denwa',
    meaning: 'telephone; phone call',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'daily-life'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '電話が鳴っている。',
      english: 'The phone is ringing.',
    },
  },
  {
    id: 'w_bentou',
    kanji: '弁当',
    kana: 'べんとう',
    romaji: 'bentou',
    meaning: 'boxed lunch; bento',
    jlptLevel: 4,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'daily-life'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: 'コンビニで弁当を買いました。',
      english: 'I bought a bento at the convenience store.',
    },
  },
  {
    id: 'w_okane',
    kanji: 'お金',
    kana: 'おかね',
    romaji: 'okane',
    meaning: 'money',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'daily-life'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'お金が足りない。',
      english: 'I don\'t have enough money.',
    },
  },
  {
    id: 'w_kagi',
    kanji: '鍵',
    kana: 'かぎ',
    romaji: 'kagi',
    meaning: 'key',
    jlptLevel: 4,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'daily-life'],
    introductionLevel: 3,
    exampleSentence: {
      japanese: 'アパートの鍵がない！',
      english: 'The apartment key is missing!',
    },
  },
  {
    id: 'w_mizu',
    kanji: '水',
    kana: 'みず',
    romaji: 'mizu',
    meaning: 'water',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'daily-life'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: '水をください。',
      english: 'Water, please.',
    },
  },
  {
    id: 'w_tabemono',
    kanji: '食べ物',
    kana: 'たべもの',
    romaji: 'tabemono',
    meaning: 'food',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'daily-life'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '食べ物はありますか？',
      english: 'Is there any food?',
    },
  },
  {
    id: 'w_kippu',
    kanji: '切符',
    kana: 'きっぷ',
    romaji: 'kippu',
    meaning: 'ticket',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'daily-life'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '切符を買ってください。',
      english: 'Please buy a ticket.',
    },
  },

  // ---------------------------------------------------------------------------
  // 5. COMMON VERBS (~10 words)
  // ---------------------------------------------------------------------------
  {
    id: 'w_iku',
    kanji: '行く',
    kana: 'いく',
    romaji: 'iku',
    meaning: 'to go',
    jlptLevel: 5,
    partOfSpeech: 'verb-godan',
    tags: ['chapter-1', 'verb'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: '学校に行きます。',
      english: 'I go to school.',
    },
  },
  {
    id: 'w_kuru',
    kanji: '来る',
    kana: 'くる',
    romaji: 'kuru',
    meaning: 'to come',
    jlptLevel: 5,
    partOfSpeech: 'verb-godan',
    tags: ['chapter-1', 'verb'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: '何かが来る！',
      english: 'Something is coming!',
    },
  },
  {
    id: 'w_miru',
    kanji: '見る',
    kana: 'みる',
    romaji: 'miru',
    meaning: 'to see; to look',
    jlptLevel: 5,
    partOfSpeech: 'verb-ichidan',
    tags: ['chapter-1', 'verb'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'あれを見て！',
      english: 'Look at that!',
    },
  },
  {
    id: 'w_taberu',
    kanji: '食べる',
    kana: 'たべる',
    romaji: 'taberu',
    meaning: 'to eat',
    jlptLevel: 5,
    partOfSpeech: 'verb-ichidan',
    tags: ['chapter-1', 'verb'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '弁当を食べます。',
      english: 'I eat the bento.',
    },
  },
  {
    id: 'w_hanasu',
    kanji: '話す',
    kana: 'はなす',
    romaji: 'hanasu',
    meaning: 'to speak; to talk',
    jlptLevel: 5,
    partOfSpeech: 'verb-godan',
    tags: ['chapter-1', 'verb'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '店員さんと話します。',
      english: 'I talk to the store clerk.',
    },
  },
  {
    id: 'w_kiku',
    kanji: '聞く',
    kana: 'きく',
    romaji: 'kiku',
    meaning: 'to listen; to ask',
    jlptLevel: 5,
    partOfSpeech: 'verb-godan',
    tags: ['chapter-1', 'verb'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '変な音が聞こえる。',
      english: 'I can hear a strange sound.',
    },
  },
  {
    id: 'w_kau',
    kanji: '買う',
    kana: 'かう',
    romaji: 'kau',
    meaning: 'to buy',
    jlptLevel: 5,
    partOfSpeech: 'verb-godan',
    tags: ['chapter-1', 'verb'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: 'コンビニで水を買います。',
      english: 'I buy water at the convenience store.',
    },
  },
  {
    id: 'w_tsukau',
    kanji: '使う',
    kana: 'つかう',
    romaji: 'tsukau',
    meaning: 'to use',
    jlptLevel: 5,
    partOfSpeech: 'verb-godan',
    tags: ['chapter-1', 'verb'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: 'この鍵を使ってください。',
      english: 'Please use this key.',
    },
  },
  {
    id: 'w_aruku',
    kanji: '歩く',
    kana: 'あるく',
    romaji: 'aruku',
    meaning: 'to walk',
    jlptLevel: 5,
    partOfSpeech: 'verb-godan',
    tags: ['chapter-1', 'verb'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '駅まで歩きます。',
      english: 'I walk to the station.',
    },
  },
  {
    id: 'w_hashiru',
    kanji: '走る',
    kana: 'はしる',
    romaji: 'hashiru',
    meaning: 'to run',
    jlptLevel: 5,
    partOfSpeech: 'verb-godan',
    tags: ['chapter-1', 'verb'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '早く走れ！',
      english: 'Run fast!',
    },
  },

  // ---------------------------------------------------------------------------
  // 6. ADJECTIVES (~6 words)
  // ---------------------------------------------------------------------------
  {
    id: 'w_ookii',
    kanji: '大きい',
    kana: 'おおきい',
    romaji: 'ookii',
    meaning: 'big; large',
    jlptLevel: 5,
    partOfSpeech: 'i-adjective',
    tags: ['chapter-1', 'adjective'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: '大きい化け物が現れた！',
      english: 'A large monster appeared!',
    },
  },
  {
    id: 'w_chiisai',
    kanji: '小さい',
    kana: 'ちいさい',
    romaji: 'chiisai',
    meaning: 'small; little',
    jlptLevel: 5,
    partOfSpeech: 'i-adjective',
    tags: ['chapter-1', 'adjective'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: '小さい声が聞こえた。',
      english: 'I heard a small voice.',
    },
  },
  {
    id: 'w_atarashii',
    kanji: '新しい',
    kana: 'あたらしい',
    romaji: 'atarashii',
    meaning: 'new',
    jlptLevel: 5,
    partOfSpeech: 'i-adjective',
    tags: ['chapter-1', 'adjective'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '新しい学生が来ました。',
      english: 'A new student has arrived.',
    },
  },
  {
    id: 'w_furui',
    kanji: '古い',
    kana: 'ふるい',
    romaji: 'furui',
    meaning: 'old (things)',
    jlptLevel: 5,
    partOfSpeech: 'i-adjective',
    tags: ['chapter-1', 'adjective'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: 'このアパートは古い。',
      english: 'This apartment is old.',
    },
  },
  {
    id: 'w_abunai',
    kanji: '危ない',
    kana: 'あぶない',
    romaji: 'abunai',
    meaning: 'dangerous',
    jlptLevel: 4,
    partOfSpeech: 'i-adjective',
    tags: ['chapter-1', 'adjective'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '夜の公園は危ない。',
      english: 'The park at night is dangerous.',
    },
  },
  {
    id: 'w_hen',
    kanji: '変',
    kana: 'へん',
    romaji: 'hen',
    meaning: 'strange; weird',
    jlptLevel: 4,
    partOfSpeech: 'na-adjective',
    tags: ['chapter-1', 'adjective', 'supernatural'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '何か変だ。',
      english: 'Something is strange.',
    },
  },
  {
    id: 'w_fushigi',
    kanji: '不思議',
    kana: 'ふしぎ',
    romaji: 'fushigi',
    meaning: 'mysterious; wonder',
    jlptLevel: 4,
    partOfSpeech: 'na-adjective',
    tags: ['chapter-1', 'adjective', 'supernatural'],
    introductionLevel: 3,
    exampleSentence: {
      japanese: '不思議なことが起きている。',
      english: 'Something mysterious is happening.',
    },
  },

  {
    id: 'w_atama',
    kanji: '頭',
    kana: 'あたま',
    romaji: 'atama',
    meaning: 'head',
    jlptLevel: 4,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'body'],
    introductionLevel: 3,
    exampleSentence: {
      japanese: '頭がいたい。',
      english: 'My head hurts.',
    },
  },

  // ---------------------------------------------------------------------------
  // 7. SUPERNATURAL / COMBAT (~8 words)
  // ---------------------------------------------------------------------------
  {
    id: 'w_bakemono',
    kanji: '化け物',
    kana: 'ばけもの',
    romaji: 'bakemono',
    meaning: 'monster; supernatural creature',
    jlptLevel: 3,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'supernatural', 'combat'],
    introductionLevel: 3,
    exampleSentence: {
      japanese: '化け物が道に現れた！',
      english: 'A monster appeared on the road!',
    },
  },
  {
    id: 'w_kougeki',
    kanji: '攻撃',
    kana: 'こうげき',
    romaji: 'kougeki',
    meaning: 'attack',
    jlptLevel: 3,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'combat'],
    introductionLevel: 3,
    exampleSentence: {
      japanese: '攻撃を選んでください。',
      english: 'Please choose an attack.',
    },
  },
  {
    id: 'w_bougyo',
    kanji: '防御',
    kana: 'ぼうぎょ',
    romaji: 'bougyo',
    meaning: 'defense',
    jlptLevel: 3,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'combat'],
    introductionLevel: 3,
    exampleSentence: {
      japanese: '防御の姿勢を取れ！',
      english: 'Take a defensive stance!',
    },
  },
  {
    id: 'w_tatakau',
    kanji: '戦う',
    kana: 'たたかう',
    romaji: 'tatakau',
    meaning: 'to fight; to battle',
    jlptLevel: 3,
    partOfSpeech: 'verb-godan',
    tags: ['chapter-1', 'combat', 'verb'],
    introductionLevel: 3,
    exampleSentence: {
      japanese: '化け物と戦う！',
      english: 'Fight the monster!',
    },
  },
  {
    id: 'w_tsuyoi',
    kanji: '強い',
    kana: 'つよい',
    romaji: 'tsuyoi',
    meaning: 'strong',
    jlptLevel: 5,
    partOfSpeech: 'i-adjective',
    tags: ['chapter-1', 'combat', 'adjective'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: 'この化け物は強い。',
      english: 'This monster is strong.',
    },
  },
  {
    id: 'w_yowai',
    kanji: '弱い',
    kana: 'よわい',
    romaji: 'yowai',
    meaning: 'weak',
    jlptLevel: 5,
    partOfSpeech: 'i-adjective',
    tags: ['chapter-1', 'combat', 'adjective'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '弱い敵だ。',
      english: 'It\'s a weak enemy.',
    },
  },
  {
    id: 'w_mahou',
    kanji: '魔法',
    kana: 'まほう',
    romaji: 'mahou',
    meaning: 'magic',
    jlptLevel: 3,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'supernatural', 'combat'],
    introductionLevel: 3,
    exampleSentence: {
      japanese: '魔法を使え！',
      english: 'Use magic!',
    },
  },
  {
    id: 'w_tairyoku',
    kanji: '体力',
    kana: 'たいりょく',
    romaji: 'tairyoku',
    meaning: 'stamina; hit points',
    jlptLevel: 3,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'combat'],
    introductionLevel: 3,
    exampleSentence: {
      japanese: '体力が少ない！',
      english: 'Stamina is low!',
    },
  },

  // ---------------------------------------------------------------------------
  // 8. PRONOUNS & DEMONSTRATIVES (~5 words)
  // ---------------------------------------------------------------------------
  {
    id: 'w_kore',
    kanji: 'これ',
    kana: 'これ',
    romaji: 'kore',
    meaning: 'this (thing near speaker)',
    jlptLevel: 5,
    partOfSpeech: 'pronoun',
    tags: ['chapter-1', 'pronoun'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'これは何ですか？',
      english: 'What is this?',
    },
  },
  {
    id: 'w_sore',
    kanji: 'それ',
    kana: 'それ',
    romaji: 'sore',
    meaning: 'that (thing near listener)',
    jlptLevel: 5,
    partOfSpeech: 'pronoun',
    tags: ['chapter-1', 'pronoun'],
    introductionLevel: 1,
  },
  {
    id: 'w_koko',
    kanji: 'ここ',
    kana: 'ここ',
    romaji: 'koko',
    meaning: 'here; this place',
    jlptLevel: 5,
    partOfSpeech: 'pronoun',
    tags: ['chapter-1', 'pronoun'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'ここは安全ですか？',
      english: 'Is it safe here?',
    },
  },
  {
    id: 'w_nani',
    kanji: '何',
    kana: 'なに',
    romaji: 'nani',
    meaning: 'what',
    jlptLevel: 5,
    partOfSpeech: 'pronoun',
    tags: ['chapter-1', 'pronoun'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'あれは何ですか？！',
      english: 'What is that?!',
    },
  },
  {
    id: 'w_dare',
    kanji: '誰',
    kana: 'だれ',
    romaji: 'dare',
    meaning: 'who',
    jlptLevel: 5,
    partOfSpeech: 'pronoun',
    tags: ['chapter-1', 'pronoun'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: 'あの人は誰？',
      english: 'Who is that person?',
    },
  },

  // ---------------------------------------------------------------------------
  // 9. FOOD & DRINK (~7 words)
  // ---------------------------------------------------------------------------
  {
    id: 'w_onigiri',
    kanji: 'おにぎり',
    kana: 'おにぎり',
    romaji: 'onigiri',
    meaning: 'rice ball',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'food'],
    introductionLevel: 1,
  },
  {
    id: 'w_yakitori',
    kanji: 'やきとり',
    kana: 'やきとり',
    romaji: 'yakitori',
    meaning: 'grilled chicken skewers',
    jlptLevel: 4,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'food'],
    introductionLevel: 1,
  },
  {
    id: 'w_taiyaki',
    kanji: 'たいやき',
    kana: 'たいやき',
    romaji: 'taiyaki',
    meaning: 'fish-shaped cake',
    jlptLevel: 4,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'food'],
    introductionLevel: 1,
  },
  {
    id: 'w_yakiguri',
    kanji: 'やきぐり',
    kana: 'やきぐり',
    romaji: 'yakiguri',
    meaning: 'roasted chestnuts',
    jlptLevel: 4,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'food'],
    introductionLevel: 1,
  },
  {
    id: 'w_ocha',
    kanji: 'お茶',
    kana: 'おちゃ',
    romaji: 'ocha',
    meaning: 'tea',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'food', 'drink'],
    introductionLevel: 1,
  },
  {
    id: 'w_koohii',
    kanji: 'コーヒー',
    kana: 'コーヒー',
    romaji: 'koohii',
    meaning: 'coffee',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'food', 'drink'],
    introductionLevel: 1,
  },
  {
    id: 'w_juusu',
    kanji: 'ジュース',
    kana: 'ジュース',
    romaji: 'juusu',
    meaning: 'juice',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'food', 'drink'],
    introductionLevel: 1,
  },

  // ---------------------------------------------------------------------------
  // 10. STATION QUEST WORDS (~5 words)
  // ---------------------------------------------------------------------------
  {
    id: 'w_onaka',
    kanji: 'おなか',
    kana: 'おなか',
    romaji: 'onaka',
    meaning: 'stomach; belly',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'daily-life'],
    introductionLevel: 1,
  },
  {
    id: 'w_suita',
    kanji: 'すいた',
    kana: 'すいた',
    romaji: 'suita',
    meaning: 'hungry; empty (past of すく)',
    jlptLevel: 5,
    partOfSpeech: 'expression',
    tags: ['chapter-1', 'daily-life'],
    introductionLevel: 1,
  },
  {
    id: 'w_ouchi',
    kanji: 'おうち',
    kana: 'おうち',
    romaji: 'ouchi',
    meaning: 'home (polite)',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'place'],
    introductionLevel: 1,
  },
  {
    id: 'w_nomimono',
    kanji: '飲み物',
    kana: 'のみもの',
    romaji: 'nomimono',
    meaning: 'drink; beverage',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'food', 'drink'],
    introductionLevel: 1,
  },
  {
    id: 'w_machi',
    kanji: '町',
    kana: 'まち',
    romaji: 'machi',
    meaning: 'town; city',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'location'],
    introductionLevel: 1,
  },
  {
    id: 'w_chotto_matte',
    kanji: 'ちょっと待って',
    kana: 'ちょっとまって',
    romaji: 'chotto matte',
    meaning: 'wait a moment',
    jlptLevel: 5,
    partOfSpeech: 'expression',
    tags: ['chapter-1', 'greeting'],
    introductionLevel: 1,
  },
  {
    id: 'w_kudasai',
    kanji: 'ください',
    kana: 'ください',
    romaji: 'kudasai',
    meaning: 'please (give me)',
    jlptLevel: 5,
    partOfSpeech: 'expression',
    tags: ['chapter-1', 'greeting'],
    introductionLevel: 1,
  },
  {
    id: 'w_douzo',
    kanji: 'どうぞ',
    kana: 'どうぞ',
    romaji: 'douzo',
    meaning: 'here you go; please (go ahead)',
    jlptLevel: 5,
    partOfSpeech: 'expression',
    tags: ['chapter-1', 'greeting'],
    introductionLevel: 1,
  },
  {
    id: 'w_omiyage',
    kanji: 'お土産',
    kana: 'おみやげ',
    romaji: 'omiyage',
    meaning: 'souvenir; gift',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'daily-life'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'お土産を買いましょう。',
      english: "Let's buy a souvenir.",
    },
  },
  {
    id: 'w_kotoba',
    kanji: '言葉',
    kana: 'ことば',
    romaji: 'kotoba',
    meaning: 'word; language',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'daily-life'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: '日本語の言葉を覚えましょう。',
      english: "Let's learn Japanese words.",
    },
  },
  {
    id: 'w_ganbatte',
    kanji: 'がんばって',
    kana: 'がんばって',
    romaji: 'ganbatte',
    meaning: 'good luck; do your best',
    jlptLevel: 5,
    partOfSpeech: 'expression',
    tags: ['chapter-1', 'greeting'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'がんばってください！',
      english: 'Please do your best!',
    },
  },
  {
    id: 'w_doko',
    kanji: 'どこ',
    kana: 'どこ',
    romaji: 'doko',
    meaning: 'where',
    jlptLevel: 5,
    partOfSpeech: 'pronoun',
    tags: ['chapter-1', 'pronoun'],
    introductionLevel: 1,
  },
  {
    id: 'w_boku',
    kanji: 'ぼく',
    kana: 'ぼく',
    romaji: 'boku',
    meaning: 'I (male)',
    jlptLevel: 5,
    partOfSpeech: 'pronoun',
    tags: ['chapter-1', 'pronoun'],
    introductionLevel: 1,
  },
  {
    id: 'w_itai',
    kanji: 'いたい',
    kana: 'いたい',
    romaji: 'itai',
    meaning: 'painful / hurts',
    jlptLevel: 5,
    partOfSpeech: 'i-adjective',
    tags: ['chapter-1', 'adjective'],
    introductionLevel: 1,
  },
  {
    id: 'w_are',
    kanji: 'あれ',
    kana: 'あれ',
    romaji: 'are',
    meaning: 'huh? / that',
    jlptLevel: 5,
    partOfSpeech: 'expression',
    tags: ['chapter-1', 'pronoun'],
    introductionLevel: 1,
  },
  {
    id: 'w_shiteta',
    kanji: 'してた',
    kana: 'してた',
    romaji: 'shiteta',
    meaning: 'was doing',
    jlptLevel: 5,
    partOfSpeech: 'verb-ichidan',
    tags: ['chapter-1', 'verb'],
    introductionLevel: 1,
  },
  {
    id: 'w_natta',
    kanji: 'なった',
    kana: 'なった',
    romaji: 'natta',
    meaning: 'became / turned into',
    jlptLevel: 5,
    partOfSpeech: 'verb-godan',
    tags: ['chapter-1', 'verb'],
    introductionLevel: 1,
  },
  {
    id: 'w_ima',
    kanji: '今',
    kana: 'いま',
    romaji: 'ima',
    meaning: 'now',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'time'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: '今、何時ですか？',
      english: 'What time is it now?',
    },
  },
  {
    id: 'w_kaerimashou',
    kanji: '帰りましょう',
    kana: 'かえりましょう',
    romaji: 'kaerimashou',
    meaning: "let's go home",
    jlptLevel: 5,
    partOfSpeech: 'verb-godan',
    tags: ['chapter-1', 'verb'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: 'もう遅いです、帰りましょう。',
      english: "It's late, let's go home.",
    },
  },

  // ---------------------------------------------------------------------------
  // 11. GIFT SHOP & POSTCARD WORDS
  // ---------------------------------------------------------------------------
  {
    id: 'w_keychain',
    kanji: 'キーホルダー',
    kana: 'キーホルダー',
    romaji: 'kiiholdaa',
    meaning: 'keychain',
    jlptLevel: 4,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'daily-life'],
    introductionLevel: 1,
  },
  {
    id: 'w_nuigurumi',
    kanji: 'ぬいぐるみ',
    kana: 'ぬいぐるみ',
    romaji: 'nuigurumi',
    meaning: 'stuffed toy; plushie',
    jlptLevel: 4,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'daily-life'],
    introductionLevel: 1,
  },
  {
    id: 'w_sticker',
    kanji: 'ステッカー',
    kana: 'ステッカー',
    romaji: 'sutekkaa',
    meaning: 'sticker',
    jlptLevel: 4,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'daily-life'],
    introductionLevel: 1,
  },
  {
    id: 'w_hagaki',
    kanji: '葉書',
    kana: 'はがき',
    romaji: 'hagaki',
    meaning: 'postcard',
    jlptLevel: 4,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'daily-life'],
    introductionLevel: 2,
    exampleSentence: {
      japanese: 'おばあちゃんに葉書を送りましょう。',
      english: "Let's send a postcard to Grandma.",
    },
  },
  {
    id: 'w_genki',
    kanji: '元気',
    kana: 'げんき',
    romaji: 'genki',
    meaning: 'well; healthy; energetic',
    jlptLevel: 5,
    partOfSpeech: 'na-adjective',
    tags: ['chapter-1', 'adjective', 'greeting'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: '元気ですか？',
      english: 'How are you?',
    },
  },
  {
    id: 'w_mainichi',
    kanji: '毎日',
    kana: 'まいにち',
    romaji: 'mainichi',
    meaning: 'every day',
    jlptLevel: 5,
    partOfSpeech: 'noun',
    tags: ['chapter-1', 'time'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: '毎日学校に行きます。',
      english: 'I go to school every day.',
    },
  },
  {
    id: 'w_tanoshii',
    kanji: '楽しい',
    kana: 'たのしい',
    romaji: 'tanoshii',
    meaning: 'fun; enjoyable',
    jlptLevel: 5,
    partOfSpeech: 'i-adjective',
    tags: ['chapter-1', 'adjective'],
    introductionLevel: 1,
    exampleSentence: {
      japanese: '日本語の勉強は楽しいです。',
      english: 'Studying Japanese is fun.',
    },
  },

  // ---------------------------------------------------------------------------
  // 12. SISTER PRESENT WORDS
  // ---------------------------------------------------------------------------
  {
    id: 'w_omocha',
    kanji: 'おもちゃ',
    kana: 'おもちゃ',
    romaji: 'omocha',
    meaning: 'toy',
    partOfSpeech: 'noun',
    jlptLevel: 5,
    tags: ['daily-life', 'chapter-1'],
    exampleSentence: { japanese: 'おもちゃ を ください', english: 'A toy, please' },
  },
  {
    id: 'w_imouto',
    kanji: 'いもうと',
    kana: 'いもうと',
    romaji: 'imouto',
    meaning: 'younger sister',
    partOfSpeech: 'noun',
    jlptLevel: 5,
    tags: ['person', 'chapter-1'],
    exampleSentence: { japanese: 'いもうと は げんき です', english: 'My younger sister is well' },
  },
  {
    id: 'w_onegaishimasu',
    kanji: 'おねがいします',
    kana: 'おねがいします',
    romaji: 'onegai shimasu',
    meaning: 'please (formal)',
    partOfSpeech: 'expression',
    jlptLevel: 5,
    tags: ['greeting', 'chapter-1'],
    exampleSentence: { japanese: 'これ を おねがいします', english: 'This one, please' },
  },
];

// =============================================================================
// Helper functions
// =============================================================================

export function getWord(id: string): Word | undefined {
  return VOCABULARY.find((w) => w.id === id);
}

export function getWordsByChapter(chapter: number): Word[] {
  return VOCABULARY.filter((w) => w.tags.includes(`chapter-${chapter}`));
}

export function getWordsByJLPT(level: 5 | 4 | 3 | 2 | 1): Word[] {
  return VOCABULARY.filter((w) => w.jlptLevel === level);
}

export function getWordsByTag(tag: string): Word[] {
  return VOCABULARY.filter((w) => w.tags.includes(tag));
}

export function getWordsByIntroductionLevel(level: number): Word[] {
  return VOCABULARY.filter((w) => w.introductionLevel <= level);
}
